package com.fendou.dao;

import com.fendou.pojo.ShippingInfo;
import java.util.List;

public interface ShippingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbg.generated
     */
    int insert(ShippingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbg.generated
     */
    ShippingInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbg.generated
     */
    List<ShippingInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShippingInfo record);
}