package com.fendou.dao;

import com.fendou.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfo record);

    UserInfo selectByNameWithPwd(@Param("username") String username, @Param("password") String password);

    int checkUsername(String username);

    String getQuestionByUsername(String username);

    String selectAnswerByUsernameAndQuestion(@Param("username") String username, @Param("question") String question);

    int updatePassword(@Param("username") String username, @Param("newPassword") String newPassword, @Param("token") String token);

    int checkEmail(@Param("email") String email);
}